version: '3'

includes:
  docker:
    taskfile: ../docker/Taskfile.yml
    internal: true

vars:
  git_root:
    sh: git rev-parse --show-toplevel
  go_version:
    sh: grep '^go ' {{.git_root}}/go.mod | awk '{print $2}'

  cache_dir: '{{.cache_dir | default ".cache"}}'
  image: 'ghcr.io/soltihq/ci/golang:{{.go_version}}'

tasks:
  _go/tool:
    internal: true
    silent: true
    requires:
      vars: [ CMD ]
    cmds:
      - cmd: mkdir -p "{{.git_root}}/{{.cache_dir}}"
      - task: docker:run
        vars:
          IMAGE: "{{.image}}"
          CMD: "{{.CMD}}"
          MOUNT_DIR: "."
          VOLUMES:
            - "{{.git_root}}/{{.cache_dir}}:/tmp/{{.cache_dir}}"
          ENVS:
            - "HOME=/tmp"
            - "GOPATH=/tmp/{{.cache_dir}}/gopath"
            - "GOMODCACHE=/tmp/{{.cache_dir}}/mod"
            - "GOCACHE=/tmp/{{.cache_dir}}/build"

  gofumpt:
    internal: true
    silent: true
    cmds:
      - task: _go/tool
        vars:
          CMD: >-
            sh -c '
              bad=$(git ls-files "*.go" | grep -v "^vendor/" | xargs -r gofumpt -l);
              if [ -n "$bad" ]; then
                echo "gofumpt: unformatted files:";
                printf "  %s\n" $bad;
                exit 1;
              fi
            '

  golangci:
    internal: true
    silent: true
    vars:
      LINT_ARGS: '{{.LINT_ARGS | default "./..."}}'
    cmds:
      - task: _go/tool
        vars:
          CMD: "golangci-lint run {{.LINT_ARGS}}"

  build:
    internal: true
    silent: true
    requires:
      vars: [ NAME ]
    vars:
      BUILD_ARGS: '{{.BUILD_ARGS | default "-trimpath -ldflags=\"-s -w\""}}'
      MAIN_PKG:   '{{.MAIN_PKG | default "./cmd"}}'
      GOARCH:     '{{.GOARCH | default "amd64"}}'
      GOOS:       '{{.GOOS | default "linux"}}'
    cmds:
      - task: _go/tool
        vars:
          CMD: >-
            sh -c 'mkdir -p bin &&
            CGO_ENABLED=0 GOOS={{.GOOS}} GOARCH={{.GOARCH}}
            go build {{.BUILD_ARGS}}
            -o bin/{{.NAME}}-{{.GOOS}}-{{.GOARCH}} {{.MAIN_PKG}}'

  govulncheck:
    internal: true
    silent: true
    vars:
      VULN_ARGS: '{{.VULN_ARGS | default "./..."}}'
    cmds:
      - task: _go/tool
        vars:
          CMD: "govulncheck {{.VULN_ARGS}}"

  test:
    internal: true
    silent: true
    vars:
      TEST_ARGS: '{{.TEST_ARGS | default "./..."}}'
    cmds:
      - task: _go/tool
        vars:
          CMD: "go test {{.TEST_ARGS}}"

  proto:
    internal: true
    silent: true
    vars:
      BUF_ARGS: '{{.BUF_ARGS | default ""}}'
    cmds:
      - task: _go/tool
        vars:
          CMD: "buf generate {{.BUF_ARGS}}"

  templ:
    internal: true
    silent: true
    vars:
      TEMPL_ARGS: '{{.TEMPL_ARGS | default ""}}'
    cmds:
      - task: _go/tool
        vars:
          CMD: "templ generate {{.TEMPL_ARGS}}"

  tailwindcss:
    internal: true
    silent: true
    requires:
      vars: [ INPUT, OUTPUT ]
    vars:
      CONFIG:        '{{.CONFIG | default "tailwind.config.cjs"}}'
      TAILWIND_ARGS: '{{.TAILWIND_ARGS | default "--minify"}}'
    cmds:
      - task: _go/tool
        vars:
          CMD: "tailwindcss -c {{.CONFIG}} -i {{.INPUT}} -o {{.OUTPUT}} {{.TAILWIND_ARGS}}"

  tidy:
    desc: Run 'go mod tidy'.
    silent: true
    cmds:
      - task: _go/tool
        vars:
          CMD: "go mod tidy"

  vendor:
    desc: Run 'go mod vendor'.
    silent: true
    cmds:
      - task: _go/tool
        vars:
          CMD: "go mod vendor"

  fmt:
    desc: Run 'gofumpt fix'.
    silent: true
    internal: true
    cmds:
      - task: _go/tool
        vars:
          CMD: sh -c 'git ls-files "*.go" | grep -v "^vendor/" | xargs -r gofumpt -l -w'
