version: '3'

includes:
  docker:
    taskfile: ../docker/Taskfile.yml
    internal: true

vars:
  git_root:
    sh: git rev-parse --show-toplevel
  rust_version:
    sh: grep -E '^rust-version[[:space:]]*=' {{.git_root}}/Cargo.toml | head -1 | awk -F'"' '{print $2}'

  cache_dir: '{{.cache_dir | default ".cache"}}'
  image: 'ghcr.io/soltihq/ci/rust:{{.rust_version}}'

tasks:
  _cargo/tool:
    internal: true
    silent: true
    requires:
      vars: [ CMD ]
    vars:
      RUSTFLAGS: '{{.RUSTFLAGS | default "-D warnings"}}'
      RUSTDOCFLAGS: '{{.RUSTDOCFLAGS | default ""}}'
    cmds:
      - cmd: mkdir -p "{{.git_root}}/{{.cache_dir}}"
      - task: docker:run
        vars:
          IMAGE: "{{.image}}"
          CMD: "{{.CMD}}"
          MOUNT_DIR: "."
          VOLUMES:
            - "{{.git_root}}/{{.cache_dir}}:/tmp/{{.cache_dir}}"
          ENVS:
            - "CARGO_TARGET_DIR=/tmp/{{.cache_dir}}/target"
            - "CARGO_HOME=/tmp/{{.cache_dir}}/cargo"
            - "RUSTUP_TOOLCHAIN={{.rust_version}}"
            - "RUSTUP_NO_UPDATE_CHECK=1"
            - "CARGO_INCREMENTAL=0"
            - "RUSTFLAGS={{.RUSTFLAGS}}"
            - "RUSTDOCFLAGS={{.RUSTDOCFLAGS}}"

  fmt:
    internal: true
    silent: true
    vars:
      FMT_ARGS: '{{.FMT_ARGS | default "--check --verbose"}}'
    cmds:
      - task: _cargo/tool
        vars:
          CMD: "fmt {{.FMT_ARGS}}"

  check:
    internal: true
    silent: true
    vars:
      CHECK_ARGS: '{{.CHECK_ARGS | default ""}}'
    cmds:
      - task: _cargo/tool
        vars:
          CMD: "check {{.CHECK_ARGS}}"

  build:
    internal: true
    silent: true
    requires:
      vars: [ CRATE ]
    vars:
      BUILD_ARGS: '{{.BUILD_ARGS | default ""}}'
    cmds:
      - task: _cargo/tool
        vars:
          CMD: "build -p {{.CRATE}} {{.BUILD_ARGS}}"

  clippy:
    internal: true
    silent: true
    vars:
      CLIPPY_ARGS: '{{.CLIPPY_ARGS | default "--all --all-features -- -D warnings"}}'
    cmds:
      - task: _cargo/tool
        vars:
          CMD: "clippy {{.CLIPPY_ARGS}}"

  test:
    internal: true
    silent: true
    vars:
      TEST_ARGS: '{{.TEST_ARGS | default "--all --all-features"}}'
    cmds:
      - task: _cargo/tool
        vars:
          CMD: "test {{.TEST_ARGS}}"

  bench:
    internal: true
    silent: true
    vars:
      BENCH_ARGS: '{{.BENCH_ARGS | default ""}}'
    cmds:
      - task: _cargo/tool
        vars:
          CMD: "bench {{.BENCH_ARGS}}"

  audit:
    internal: true
    silent: true
    cmds:
      - task: _cargo/tool
        vars:
          CMD: "audit"

  publish-dry-run:
    internal: true
    silent: true
    requires:
      vars: [ CRATE ]
    vars:
      PUBLISH_ARGS: '{{.PUBLISH_ARGS | default "--all-features"}}'
    cmds:
      - task: _cargo/tool
        vars:
          CMD: "publish --dry-run -p {{.CRATE}} {{.PUBLISH_ARGS}}"

  package-list:
    internal: true
    silent: true
    requires:
      vars: [ CRATE ]
    vars:
      PACKAGE_ARGS: '{{.PACKAGE_ARGS | default "--locked"}}'
    cmds:
      - task: _cargo/tool
        vars:
          CMD: "package --list -p {{.CRATE}} {{.PACKAGE_ARGS}}"

  doc:
    internal: true
    silent: true
    vars:
      DOC_ARGS: '{{.DOC_ARGS | default ""}}'
    cmds:
      - task: _cargo/tool
        vars:
          RUSTDOCFLAGS: "-D warnings"
          CMD: "doc {{.DOC_ARGS}}"

  docs:
    internal: true
    silent: true
    vars:
      MANIFEST_PATH: '{{if .MANIFEST_PATH}}{{.MANIFEST_PATH}}{{else if .CRATE}}crates/{{.CRATE}}/Cargo.toml{{else}}Cargo.toml{{end}}'
      DOCS_ARGS: '{{.DOCS_ARGS | default "--all-features"}}'
    cmds:
      - task: _cargo/tool
        vars:
          RUSTFLAGS: "--cap-lints warn"
          CMD: >-
            +nightly rustdoc --lib --manifest-path {{.MANIFEST_PATH}} {{.DOCS_ARGS}}
            -Zrustdoc-map -Zunstable-options -Zrustdoc-scrape-examples
            --config 'build.rustdocflags=["--cfg","docsrs","-Z","unstable-options","--cap-lints","warn"]'

  fmt/fix:
    desc: Run 'cargo fmt' (auto-format).
    silent: true
    vars:
      FMT_ARGS: '{{.FMT_ARGS | default ""}}'
    cmds:
      - task: _cargo/tool
        vars:
          CMD: "fmt {{.FMT_ARGS}}"

  audit/fix:
    desc: Run 'audit' with auto fix.
    silent: true
    cmds:
      - task: _cargo/tool
        vars:
          CMD: "audit fix"
