name: GHCR Build
description: Build and Push docker image.

inputs:
  docker_username:
    description: 'Docker auth username'
    required: true
  docker_password:
    description: 'Docker auth password'
    required: true
  image:
    description: 'Image name / Taskfile command'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ inputs.docker_username }}
        password: ${{ inputs.docker_password }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Buildx
      uses: docker/setup-buildx-action@v3
      with:
        install: true

    - name: Invoke Taskfile
      uses: soltiHQ/actions/taskfile@main
      with:
        command: ${{ inputs.image }}
