version: '3'

tasks:
  download/file:
    internal: true
    silent: true
    requires:
      vars: [ URL, TO ]
    cmds:
      - |
        if [ ! -f "{{.TO}}" ]; then
          mkdir -p "$(dirname "{{.TO}}")"
          curl -fsSL -o "{{.TO}}" "{{.URL}}"
        fi
